workflows:
  flutter-multiplatform:
    name: Flutter Multi-Platform CI/CD
    max_build_duration: 120
    triggering:
      events:
        - push
      branch_patterns:
        - pattern: main
          include: true
          source: true
        - pattern: develop
          include: true
          source: true
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
      android: true
      vars:
        GITHUB_TOKEN: Encrypted(...) # <-- à configurer dans Codemagic
    scripts:
      # 🔹 Setup Flutter
      - name: Flutter clean & get
        script: |
          flutter clean
          flutter pub get

      # 🔹 Créer plateformes si manquantes
      - name: Ensure platforms exist
        script: |
          flutter create --platforms=ios,android .

      # 🔹 Installer CocoaPods
      - name: Install CocoaPods
        script: |
          cd ios
          pod install
          cd ..

      # 🔹 Build Android APK & AAB
      - name: Build Android
        script: |
          flutter build apk --release
          flutter build appbundle --release

      # 🔹 Build iOS (sans signature si aucun certificat n’est fourni)
      - name: Build iOS
        script: |
          flutter build ios --release --no-codesign

      # 🔹 (Optionnel) Code signing iOS
      - name: iOS Code Signing
        script: |
          echo "⚡ Ajoute tes certificats Apple pour signer l'app iOS"
        ignore_failure: true

      # 🔹 (Optionnel) Code signing Android
      - name: Android Code Signing
        script: |
          echo "⚡ Ajoute ton keystore Android pour signer l'APK/AAB"
        ignore_failure: true

      # 🔹 Upload vers GitHub Releases
      - name: Publish to GitHub Releases
        script: |
          TAG_NAME="build-$(date +'%Y%m%d-%H%M%S')"
          gh release create $TAG_NAME build/app/outputs/flutter-apk/*.apk build/app/outputs/bundle/release/*.aab build/ios/iphoneos/**/*.app --title "Build $TAG_NAME"
    artifacts:
      - build/ios/iphoneos/**/*.app
      - build/app/outputs/flutter-apk/*.apk
      - build/app/outputs/bundle/release/*.aab
