name: myjantes_flutter
description: MY JANTES - Expert en rénovation de jantes aluminium
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.16.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  http: ^1.1.0
  shared_preferences: ^2.2.2
  image_picker: ^1.0.4
  cached_network_image: ^3.3.0
  url_launcher: ^6.2.1
  intl: ^0.18.1
  provider: ^6.1.1
  go_router: ^12.1.3
  flutter_secure_storage: ^9.0.0
  connectivity_plus: ^5.0.1
  google_fonts: ^6.1.0
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.3.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/logo.png"
  min_sdk_android: 21
  web:
    generate: true
    image_path: "assets/icons/logo.png"
    background_color: "#ffffff"
    theme_color: "#DC2626"

flutter_native_splash:
  color: "#ffffff"
  image: assets/icons/logo.png
  branding: assets/icons/logo.png
  android_12:
    color: "#ffffff"
    image: assets/icons/logo.png