[deployment]
run = ["python3", "main.py"]
deploymentTarget = "cloudrun"
build = ["bash", "-c", "cd flutter_app && (flutter clean && flutter pub get && flutter build web --release --web-renderer html) || echo 'Flutter build failed, using fallback' && cd .. && echo 'Build command completed'"]

[env]
PYTHON_UNBUFFERED = "1"
PORT = "5000"
REPL_DEPLOYMENT = "true"
FLUTTER_WEB_AUTO_DETECT = "true"

[cloudrun]
memory = "2Gi"
cpu = "2"
minInstances = 1
maxInstances = 10
concurrency = 100
port = 5000
timeoutSeconds = 300